import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { PageHeader } from "@/components/layout/AppShell";
import { inspectionService } from "@/services/inspectionService";
import { ModelStatusBanner } from "@/components/model/ModelStatusBanner";
export const Route = createFileRoute("/_authenticated/model")({ component: Model });
function Model() {
  const q = useQuery({ queryKey: ["model"], queryFn: inspectionService.model, enabled: inspectionService.isConfigured(), retry: false });
  const health = useQuery({ queryKey: ["model-health"], queryFn: inspectionService.health, enabled: inspectionService.isConfigured(), retry: false });
  return (
    <>
      <PageHeader
        title="Model"
        description="Inference service and model metadata. No benchmark claims are generated by the UI."
      />
      <ModelStatusBanner />
      <div className="panel p-6">
        {q.data ? (
          <div className="grid gap-4 sm:grid-cols-2">
            <Info label="Name" value={q.data.name} />
            <Info label="Version" value={q.data.version} />
            <Info label="Status" value={q.data.status} />
            <Info label="Service" value={health.data?.model_loaded ? "Loaded" : "Unavailable"} />
            <Info label="Model hash" value={q.data.hash ?? "—"} />
            <Info label="Device" value={q.data.device ?? "—"} />
            <div className="sm:col-span-2">
              <p className="mono-label">Supported classes</p>
              <div className="mt-2 flex flex-wrap gap-2">
                {q.data.classes.map((c) => (
                  <span key={c} className="rounded border border-border px-2 py-1 text-xs">
                    {c}
                  </span>
                ))}
              </div>
            </div>
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">
            Model metadata is unavailable until the inference service is configured and reachable.
          </p>
        )}
      </div>
    </>
  );
}
function Info({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="mono-label">{label}</p>
      <p className="mt-1">{value}</p>
    </div>
  );
}
